apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
spec:
  template:
    spec:
      containers:
      - name: sleeper
        image: busybox
        command: ["sleep",  "10"]
      restartPolicy: Never
  backoffLimit: 4
